// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_dolce_gabana_png);    // assets/dolce_gabana.png
LV_IMG_DECLARE(ui_img_tom_ford_taboco_vanile_png);    // assets/Tom ford taboco vanile.png
LV_IMG_DECLARE(ui_img_lanvin_png);    // assets/lanvin.png
LV_IMG_DECLARE(ui_img_1419945142);    // assets/Dior-savuage.png
LV_IMG_DECLARE(ui_img_1139839843);    // assets/error-report-failed-test-icon-vector-34954659 (1).png
LV_IMG_DECLARE(ui_img_521946201);    // assets/istockphoto-1175046548-170667a (1).png
LV_IMG_DECLARE(ui_img_1123770958);    // assets/ChatGPT Image 29 окт. 2025 г., 04_43_56.png
LV_IMG_DECLARE(ui_img_625556972);    // assets/fdsf (1).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
