// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_web1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_web2 = NULL;
lv_obj_t * ui_web3 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_web4 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 317);
    lv_obj_set_height(ui_Panel2, 45);
    lv_obj_set_x(ui_Panel2, -3);
    lv_obj_set_y(ui_Panel2, -209);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -84);
    lv_obj_set_y(ui_Label1, -210);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "0");

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_dolce_gabana_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 78);
    lv_obj_set_y(ui_Image2, -70);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 270);
    lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0x7ABDE4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Image2, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_tom_ford_taboco_vanile_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -80);
    lv_obj_set_y(ui_Image3, -70);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 270);
    lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0x7ABDE4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Image3, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_lanvin_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 77);
    lv_obj_set_y(ui_Image4, 137);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 270);
    lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0x7ABDE4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Image4, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_1419945142);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -81);
    lv_obj_set_y(ui_Image5, 137);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 270);
    lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x7ABDE4), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Image5, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -124);
    lv_obj_set_y(ui_Label9, -210);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Sepish :");

    ui_web1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_web1, LV_SIZE_CONTENT);   /// 5
    lv_obj_set_height(ui_web1, LV_SIZE_CONTENT);    /// 5
    lv_obj_set_x(ui_web1, -81);
    lv_obj_set_y(ui_web1, 5);
    lv_obj_set_align(ui_web1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_web1, "5.000");

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1000
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1000
    lv_obj_set_x(ui_Label11, -151);
    lv_obj_set_y(ui_Label11, -158);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "1");

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 16);
    lv_obj_set_y(ui_Label12, -158);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "2");

    ui_web2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_web2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_web2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_web2, 76);
    lv_obj_set_y(ui_web2, 5);
    lv_obj_set_align(ui_web2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_web2, "7.000");

    ui_web3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_web3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_web3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_web3, -81);
    lv_obj_set_y(ui_web3, 229);
    lv_obj_set_align(ui_web3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_web3, "8.000");

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -151);
    lv_obj_set_y(ui_Label15, 45);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "3");

    ui_Label21 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 14);
    lv_obj_set_y(ui_Label21, 45);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "4");

    ui_web4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_web4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_web4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_web4, 76);
    lv_obj_set_y(ui_web4, 229);
    lv_obj_set_align(ui_web4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_web4, "10.000");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel2 = NULL;
    ui_Label1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Label9 = NULL;
    ui_web1 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_web2 = NULL;
    ui_web3 = NULL;
    ui_Label15 = NULL;
    ui_Label21 = NULL;
    ui_web4 = NULL;

}
